sonar.projectKey=Lodres_civiconnect
sonar.organization=lodres
sonar.projectName=CiviConnect
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
